algoritmo "exemplo funcao salario"
var
   horas:inteiro
   valor_hora:real
inicio
  funcao calculo_salario():real
  var
      salario:real
  inicio
      
      salario <- a*v
      
      retorne salario
  fimfuncao
//chamando a funcao
escreva("Informe a quantidade de horas trabalhadas:")
leia(horas)
escreva("Informe o valor recebido por hora trabalhada:")
leia(valor_hora)
escreval("O salário a receber é de : ",calculo_salario(horas,valor_hora))
fimalgoritmo
